"""Dynamic Manim scene generation and rendering via subprocess."""

import os
import shutil
import subprocess
import sys
import textwrap
import uuid
from pathlib import Path

import numpy as np
from manim import Scene

from formula2manim.config import DEFAULT_QUALITY, QUALITY_MAP
from formula2manim.exceptions import RenderingError

# Template using MathTex (requires LaTeX on the system).
SCENE_TEMPLATE_LATEX = '''\
"""Auto-generated by Formula2Manim — safe to delete."""

from manim import *
import numpy as np


class {scene_class_name}(Scene):
    {bg_color_attr}
    def construct(self):
        trajectory = np.array({trajectory_data})

        x_vals = trajectory[:, 0]
        y_vals = trajectory[:, 1]

        x_min, x_max = float(x_vals.min()), float(x_vals.max())
        y_min, y_max = float(y_vals.min()), float(y_vals.max())

        x_pad = max(1.0, (x_max - x_min) * 0.15)
        y_pad = max(1.0, (y_max - y_min) * 0.15)

        axes = Axes(
            x_range=[x_min - x_pad, x_max + x_pad, {x_step}],
            y_range=[y_min - y_pad, y_max + y_pad, {y_step}],
            axis_config={{"include_numbers": True, "font_size": 24}},
            tips=False,
        )
        axes_labels = axes.get_axis_labels({x_label_dict}, {y_label_dict})
        self.add(axes, axes_labels)

        points = [axes.c2p(float(x), float(y)) for x, y in trajectory]
        traj = VMobject(color={trajectory_color})
        traj.set_points_smoothly(points)

        dot = Dot(
            point=axes.c2p(float(trajectory[0, 0]), float(trajectory[0, 1])),
            radius={dot_radius},
            color={dot_color},
        )
        self.add(dot)

        label = MathTex(r"{label_text}", font_size=24)
        label.to_corner(UR, buff=0.3)
        self.add(label)

        {params_block}

        self.wait(0.3)
        self.play(
            Create(traj),
            MoveAlongPath(dot, traj),
            run_time={run_time},
            rate_func=linear,
        )
        self.wait(2)
'''

# Template using Text exclusively — no LaTeX required at all.
SCENE_TEMPLATE_TEXT = '''\
"""Auto-generated by Formula2Manim — safe to delete."""

from manim import *
import numpy as np


class {scene_class_name}(Scene):
    {bg_color_attr}
    def construct(self):
        trajectory = np.array({trajectory_data})

        x_vals = trajectory[:, 0]
        y_vals = trajectory[:, 1]

        x_min, x_max = float(x_vals.min()), float(x_vals.max())
        y_min, y_max = float(y_vals.min()), float(y_vals.max())

        x_pad = max(1.0, (x_max - x_min) * 0.15)
        y_pad = max(1.0, (y_max - y_min) * 0.15)

        x_step = {x_step}
        y_step = {y_step}

        axes = Axes(
            x_range=[x_min - x_pad, x_max + x_pad, x_step],
            y_range=[y_min - y_pad, y_max + y_pad, y_step],
            axis_config={{"include_numbers": False, "font_size": 24}},
            tips=False,
        )
        self.add(axes)

        # Axis labels using Text (no LaTeX)
        x_label = Text("{x_label}", font_size=24, color=WHITE)
        x_label.next_to(axes.x_axis.get_end(), DOWN, buff=0.3)
        self.add(x_label)

        y_label = Text("{y_label}", font_size=24, color=WHITE)
        y_label.next_to(axes.y_axis.get_end(), LEFT, buff=0.3)
        self.add(y_label)

        # Manual axis number ticks
{tick_marks_block}

        points = [axes.c2p(float(x), float(y)) for x, y in trajectory]
        traj = VMobject(color={trajectory_color})
        traj.set_points_smoothly(points)

        dot = Dot(
            point=axes.c2p(float(trajectory[0, 0]), float(trajectory[0, 1])),
            radius={dot_radius},
            color={dot_color},
        )
        self.add(dot)

        label = Text("{label_text}", font_size=20, color=WHITE)
        label.to_corner(UR, buff=0.3)
        self.add(label)

        {params_block}

        self.wait(0.3)
        self.play(
            Create(traj),
            MoveAlongPath(dot, traj),
            run_time={run_time},
            rate_func=linear,
        )
        self.wait(2)
'''


def _has_latex() -> bool:
    """Check if LaTeX (pdflatex or latex) is available on the system."""
    return shutil.which("pdflatex") is not None or shutil.which("latex") is not None


def _nice_step(range_width: float) -> float:
    """Compute a clean axis step size given the range width."""
    if range_width <= 0:
        return 1.0
    magnitude = 10 ** np.floor(np.log10(range_width))
    residual = range_width / magnitude
    if residual <= 1.5:
        step = magnitude * 0.5
    elif residual <= 3:
        step = magnitude
    elif residual <= 7:
        step = magnitude * 2
    else:
        step = magnitude * 5
    return float(step)


def _generate_tick_marks_code(
    x_min: float, x_max: float, x_step: float,
    y_min: float, y_max: float, y_step: float,
) -> str:
    """Generate Python source for manual tick mark labels using Text.
    Caller provides base indentation; we must NOT include leading whitespace.
    """
    lines: list[str] = []
    # X-axis tick marks
    x = x_min
    while x <= x_max + x_step * 0.5:
        val_str = f"{x:g}"
        idx = len(lines)
        lines.append(
            f'xt_{idx} = Text("{val_str}", font_size=18, color=WHITE)'
        )
        lines.append(
            f'xt_{idx}.next_to(axes.c2p({x}, 0), DOWN, buff=0.15)'
        )
        lines.append(
            f'self.add(xt_{idx})'
        )
        x += x_step
    # Y-axis tick marks (skip 0 since x-axis already marks origin)
    y = y_min
    while y <= y_max + y_step * 0.5:
        if abs(y) < y_step * 0.01:
            y += y_step
            continue
        val_str = f"{y:g}"
        idx = len(lines)
        lines.append(
            f'yt_{idx} = Text("{val_str}", font_size=18, color=WHITE)'
        )
        lines.append(
            f'yt_{idx}.next_to(axes.c2p(0, {y}), LEFT, buff=0.15)'
        )
        lines.append(
            f'self.add(yt_{idx})'
        )
        y += y_step
    return "\n".join(lines) if lines else "pass"


def _format_params_text(params: dict[str, float]) -> str:
    """Format parameter dict as a display string."""
    parts = [f"{k}={v}" for k, v in params.items()]
    return ", ".join(parts)


def create_scene_class(
    trajectory: np.ndarray,
    t_range: tuple[float, float],
    latex_label: str,
    x_label: str = "x",
    y_label: str = "y",
    enhancements: dict | None = None,
    params_label: str = "",
) -> type[Scene]:
    """Placeholder — actual rendering uses build_and_render()."""
    return Scene


def build_and_render(
    trajectory: np.ndarray,
    t_range: tuple[float, float],
    latex_label: str,
    params: dict[str, float] | None = None,
    x_label: str = "x",
    y_label: str = "y",
    output_dir: str | Path = "./outputs",
    fps: int = 30,
    quality: str = DEFAULT_QUALITY,
    enhancements: dict | None = None,
) -> str:
    """Generate a Manim scene file and render it to MP4 via subprocess."""
    enhancements = enhancements or {}
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    uid = uuid.uuid4().hex[:8]
    scene_class_name = f"Formula2ManimScene_{uid}"
    scene_file_path = output_dir / f"__f2m_{uid}.py"

    x_vals = trajectory[:, 0]
    y_vals = trajectory[:, 1]
    x_min, x_max = float(x_vals.min()), float(x_vals.max())
    y_min, y_max = float(y_vals.min()), float(y_vals.max())
    x_step = _nice_step(x_max - x_min)
    y_step = _nice_step(y_max - y_min)

    dot_color = enhancements.get("dot_color", "RED")
    trajectory_color = enhancements.get("trajectory_color", "YELLOW")
    bg_color = enhancements.get("background_color", None)
    dot_radius = enhancements.get("dot_radius", 0.08)

    # Format colors correctly for Manim source code.
    # Named colors (RED, YELLOW) stay bare; hex colors get quoted.
    def _fmt_color(c: str) -> str:
        return f'"{c}"' if c.startswith("#") else c

    dot_color_fmt = _fmt_color(dot_color)
    trajectory_color_fmt = _fmt_color(trajectory_color)

    bg_color_attr = ""
    if bg_color:
        if bg_color.startswith("#"):
            bg_color_attr = f'background_color = "{bg_color}"'
        else:
            bg_color_attr = f"background_color = {bg_color}"

    use_latex = _has_latex()

    # Build params block
    if params:
        if use_latex:
            param_parts = []
            for k, v in params.items():
                k_escaped = k.replace("_", r"\_")
                param_parts.append(f"{k_escaped}={{{v}}}")
            params_label = r",\ ".join(param_parts)
            params_block = (
                'params_text = MathTex(r"{}", font_size=20, color=GRAY)\n'
                '        params_text.next_to(label, DOWN, buff=0.15, aligned_edge=RIGHT)\n'
                '        self.add(params_text)'
            ).format(params_label)
        else:
            params_label = _format_params_text(params)
            params_block = (
                'params_text = Text("{}", font_size=16, color=GRAY)\n'
                '        params_text.next_to(label, DOWN, buff=0.15, aligned_edge=RIGHT)\n'
                '        self.add(params_text)'
            ).format(params_label)
    else:
        params_block = ""

    # Choose template and label
    if use_latex:
        template = SCENE_TEMPLATE_LATEX
        label_text = latex_label.replace("\\", "\\\\")
        x_label_str = f'x_label="{x_label}"'
        y_label_str = f'y_label="{y_label}"'
        tick_marks_block = ""
    else:
        template = SCENE_TEMPLATE_TEXT
        # Convert LaTeX to readable text
        label_text = latex_label.replace("\\\\", " ; ")
        for char in ["{", "}", "\\", "_"]:
            label_text = label_text.replace(char, "")
        label_text = label_text.replace("^", "^")
        x_label_str = x_label
        y_label_str = y_label

        x_pad = max(1.0, (x_max - x_min) * 0.15)
        y_pad = max(1.0, (y_max - y_min) * 0.15)
        tick_marks_block = textwrap.indent(
            _generate_tick_marks_code(
                x_min - x_pad, x_max + x_pad, x_step,
                y_min - y_pad, y_max + y_pad, y_step,
            ),
            "        ",
        )

    traj_repr = repr(trajectory.tolist())
    run_time = t_range[1] - t_range[0]

    source = template.format(
        scene_class_name=scene_class_name,
        trajectory_data=traj_repr,
        x_step=x_step,
        y_step=y_step,
        x_label_dict=x_label_str,
        y_label_dict=y_label_str,
        x_label=x_label_str,
        y_label=y_label_str,
        trajectory_color=trajectory_color_fmt,
        dot_color=dot_color_fmt,
        dot_radius=dot_radius,
        label_text=label_text,
        params_block=params_block,
        run_time=run_time,
        bg_color_attr=bg_color_attr,
        tick_marks_block=tick_marks_block,
    )

    scene_file_path.write_text(source, encoding="utf-8")

    try:
        compile(source, str(scene_file_path), "exec")
    except SyntaxError as e:
        raise RenderingError(
            f"Generated scene file has a syntax error: {e}\n"
            f"File: {scene_file_path}"
        ) from e

    quality_flag = f"-q{quality}"
    cmd = [
        sys.executable, "-m", "manim",
        "render",
        quality_flag,
        "--fps", str(fps),
        "--media_dir", str(output_dir.resolve()),
        str(scene_file_path.resolve()),
        scene_class_name,
    ]

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            encoding="utf-8",
            timeout=300,
            cwd=str(output_dir),
            env={**os.environ, "PYTHONIOENCODING": "utf-8"},
        )
    except subprocess.TimeoutExpired:
        raise RenderingError(
            "Manim rendering timed out after 300 seconds. "
            "Try reducing --num-points or using a shorter --t-range."
        )

    if result.returncode != 0:
        stderr = result.stderr or result.stdout or ""
        raise RenderingError(
            f"Manim rendering failed with exit code {result.returncode}.\n\n"
            f"STDERR/STDOUT:\n{stderr[-2000:]}"
        )

    # Locate output video
    quality_dir = QUALITY_MAP.get(quality, "720p30")
    video_dir = output_dir / "videos" / f"__f2m_{uid}" / quality_dir
    video_path = video_dir / f"{scene_class_name}.mp4"

    if not video_path.exists():
        candidates = list(output_dir.rglob(f"{scene_class_name}.mp4"))
        if candidates:
            video_path = candidates[0]
        else:
            raise RenderingError(
                f"Rendering appeared to succeed but video not found. "
                f"Expected: {video_path}"
            )

    return str(video_path.resolve())
